// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCLAB_API.Data;

#nullable disable

namespace SCLAB_API.Migrations
{
    [DbContext(typeof(SisComputoDbContext))]
    [Migration("20251104142941_InitialCreate7")]
    partial class InitialCreate7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCLAB_API.Models.Alerta", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaId"));

                    b.Property<int>("CreadaPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("EstadoAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("int");

                    b.Property<int?>("ResueltoPor")
                        .HasColumnType("int");

                    b.Property<string>("SolucionDescripcion")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("SolucionTipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlertaId");

                    b.HasIndex("CreadaPor");

                    b.HasIndex("EstadoAlerta");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("ResueltoPor");

                    b.ToTable("Alerta");
                });

            modelBuilder.Entity("SCLAB_API.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<int?>("CronogramaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("RegistroPor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RolRegistro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("CronogramaId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("Tipo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("SCLAB_API.Models.CronogramaInterval", b =>
                {
                    b.Property<int>("CronogramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CronogramaId"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacion")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("CronogramaId");

                    b.HasIndex("LaboratorioId", "DiaSemana");

                    b.ToTable("CronogramaInterval");
                });

            modelBuilder.Entity("SCLAB_API.Models.Laboratorio", b =>
                {
                    b.Property<int>("LaboratorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaboratorioId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoLaboratorio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LaboratorioId");

                    b.HasIndex("CodigoLaboratorio")
                        .IsUnique();

                    b.ToTable("Laboratorio");
                });

            modelBuilder.Entity("SCLAB_API.Models.LogActividad", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Detalle")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogActividad");
                });

            modelBuilder.Entity("SCLAB_API.Models.Maquina", b =>
                {
                    b.Property<int>("MaquinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaquinaId"));

                    b.Property<string>("CodigoMaquina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescripcionHardware")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("LaboratorioId")
                        .HasColumnType("int");

                    b.Property<string>("Qr")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("MaquinaId");

                    b.HasIndex("CodigoMaquina")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("LaboratorioId");

                    b.ToTable("Maquina");
                });

            modelBuilder.Entity("SCLAB_API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CI")
                        .IsUnique();

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SCLAB_API.Models.Alerta", b =>
                {
                    b.HasOne("SCLAB_API.Models.Usuario", "UsuarioCreador")
                        .WithMany("AlertasCreadas")
                        .HasForeignKey("CreadaPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCLAB_API.Models.Laboratorio", "Laboratorio")
                        .WithMany("Alertas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SCLAB_API.Models.Maquina", "Maquina")
                        .WithMany("Alertas")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCLAB_API.Models.Usuario", "UsuarioResolutor")
                        .WithMany("AlertasResueltas")
                        .HasForeignKey("ResueltoPor")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Laboratorio");

                    b.Navigation("Maquina");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioResolutor");
                });

            modelBuilder.Entity("SCLAB_API.Models.Asistencia", b =>
                {
                    b.HasOne("SCLAB_API.Models.CronogramaInterval", "Cronograma")
                        .WithMany("Asistencias")
                        .HasForeignKey("CronogramaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SCLAB_API.Models.Laboratorio", "Laboratorio")
                        .WithMany("Asistencias")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCLAB_API.Models.Maquina", "Maquina")
                        .WithMany("Asistencias")
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SCLAB_API.Models.Usuario", "Usuario")
                        .WithMany("Asistencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cronograma");

                    b.Navigation("Laboratorio");

                    b.Navigation("Maquina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SCLAB_API.Models.CronogramaInterval", b =>
                {
                    b.HasOne("SCLAB_API.Models.Laboratorio", "Laboratorio")
                        .WithMany("Cronogramas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("SCLAB_API.Models.LogActividad", b =>
                {
                    b.HasOne("SCLAB_API.Models.Usuario", "Usuario")
                        .WithMany("LogActividades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SCLAB_API.Models.Maquina", b =>
                {
                    b.HasOne("SCLAB_API.Models.Laboratorio", "Laboratorio")
                        .WithMany("Maquinas")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratorio");
                });

            modelBuilder.Entity("SCLAB_API.Models.CronogramaInterval", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("SCLAB_API.Models.Laboratorio", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Asistencias");

                    b.Navigation("Cronogramas");

                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("SCLAB_API.Models.Maquina", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("SCLAB_API.Models.Usuario", b =>
                {
                    b.Navigation("AlertasCreadas");

                    b.Navigation("AlertasResueltas");

                    b.Navigation("Asistencias");

                    b.Navigation("LogActividades");
                });
#pragma warning restore 612, 618
        }
    }
}
